#!/bin/bash
export PATH="/opt/anaconda3/bin/$PATH"
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
pyini () {
	__conda_setup="$('/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
	if [ $? -eq 0 ]
	then
		eval "$__conda_setup"
	else
		if [ -f "/opt/anaconda3/etc/profile.d/conda.sh" ]
		then
			. "/opt/anaconda3/etc/profile.d/conda.sh"
		else
			export PATH="/opt/anaconda3/bin:$PATH"
		fi
	fi
	unset __conda_setup
}
pyini
python tui_app.py
